config/routes.rb
Trackerapp::Application.routes.draw do

  root to: "entries#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  resources :entries do
    get :autocomplete_project_name, :on => :collection
  end

  get 'settings', to: 'users#edit'

  resource :user do
    collection do
      patch :update_settings
      post :update_settings
      get :update_settings
      patch :update_password
      get :update_password
      post :update_password
    end
  end

  namespace :admin do
    get '/' => "admin#index"
    resources :projects
    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :entries
  has_many :salaries
  has_many :project_users
  has_many :projects, :through => :project_users

  validates_uniqueness_of :email
  validates_uniqueness_of :username
  validates :username, :email, :presence => true, :allow_nil => false
  validates :password, :presence => true,  :confirmation => true, :on => :create
  validates :password_confirmation, :presence => true, :on => :create
  validates_inclusion_of :language, :in => %w( en cs ), :message => I18n.t("users.language_has_to_be")

  serialize :settings, Hash

  after_save :save_salary_history

  def new_entries
    provider.all
  end

  def type_in_words
    admin? ? I18n.t('users.admin') : I18n.t('users.soldier')
  end

  def save_salary_history
    if current_salary_changed?
      self.salaries.each do |salary|
        if salary.ended_at.nil?
          salary.ended_at = DateTime.current
          salary.save
        end
      end

      new_salary = Salary.new
      new_salary.value = current_salary
      new_salary.user_id = id
      new_salary.ended_at = nil
      new_salary.save
    end
  end

  private
  def provider
    "Entry::#{provider_type.classify}Provider".constantize.new(settings[provider_type.to_sym])
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:user][:admin] == "1"
      @user.admin = true
    end

    if @user.save
      redirect_to admin_path, :notice => t('users.user_created')
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to edit_admin_user_path, :notice => t('users.user_updated')
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_path, :notice => t('users.user_deleted')
  end

  def show
    @user = User.find(params[:id])

    @from = if params[:from].present?
              Date.parse(params[:from])
            else
              Date.new(Date.current.year, Date.current.month, 1)
            end

    @previous_month = (@from - 1.month).at_beginning_of_month
    @next_month = (@from + 1.month).at_beginning_of_month

    @entries = Entry.for_user(@user).between(@from, @next_month).by_date
    @total = @entries.sum(:minutes)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin, :language, :current_salary)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  def edit
    @user = current_user

    @settings_form ||= SettingsForm.new(current_user)
    @password_form ||= PasswordForm.new(current_user)
  end

  def update_password
    @user = current_user

    @password_form = PasswordForm.new(current_user, password_form_params)
    @settings_form ||= SettingsForm.new(current_user)

    if @password_form.submit
      redirect_to settings_path, :notice => t('users.password_changed')
    else
      render :edit
    end
  end

  def update_settings
    @user = current_user

    @settings_form = SettingsForm.new(current_user, settings_form_params)
    @password_form ||= PasswordForm.new(current_user)

    if @settings_form.submit
      redirect_to settings_path, :notice => t('users.settings_updated')
    else
      render :edit
    end
  end

  private

  def password_form_params
    params.require(:password_form).
      permit(:password, :password_confirmation)
  end

  def settings_form_params
    params.require(:settings_form).
      permit(:username, :email, :language)
  end
end

app/views/users/_form.html.erb
<div class="container">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="col-lg-5">
      <div class="input-group">
        <%= f.label :username, class: "input-group-addon" %>
        <%= f.text_field :username, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :email, class: "input-group-addon" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :password, class: "input-group-addon" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :password_confirmation, class: "input-group-addon" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="input-group">
        <%= f.label :admin, class: "checkbox" do %>
          <%= f.check_box :admin, class: "checkbox inline" %>Admin?
        <% end %>
      </div>
      <div class="input-group">
          <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_password_form.html.slim
= form_for @password_form, :url => update_password_user_path, html: { id: 'user-form', class: 'form-horizontal'} do |f|

  = render 'layouts/errors', object: @password_form

  .form-group
    = f.label :password, t('users.password'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.password_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation, t('users.password_confirmation'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.password_field :password_confirmation, class: 'form-control'

  .form-group
    .col-sm-offset-4.col-sm-4
      = f.submit t('users.update'), class: 'btn btn-default'

app/views/users/_settings_form.html.slim
= form_for @settings_form, :url => update_settings_user_path, html: { id: 'user-form', class: 'form-horizontal'} do |f|

  = render 'layouts/errors', object: @settings_form

  .form-group
    = f.label :username, t('users.username'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :username, class: 'form-control'

  .form-group
    = f.label :email, t('users.email'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :email, class: 'form-control'

  .form-group
    = f.label :language, t('users.language'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :language, class: 'form-control'

  .form-group
    .col-sm-offset-4.col-sm-4
      = f.submit t('users.update'), class: 'btn btn-default'

app/views/users/edit.html.slim
= title t('common.settings')

.box

  h1 = "#{t('users.settings')}"

  h3 = "#{t('users.edit_settings')}"

  = render 'settings_form'

  h3 = "#{t('users.change_password')}"

  = render 'password_form'

app/views/users/index.html.erb
<%= render "form" %>

<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td>
          <div class="pull-right">
            <%= link_to user_path(user), :class => 'btn btn-default btn-sm' do %>
              <span class="glyphicon glyphicon-zoom-in"></span>
              View
            <% end %>
            <%= link_to edit_user_path(user), :class => 'btn btn-default btn-sm' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>
            <%= link_to user_path(user),
                    method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-default btn-sm' do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>