config/routes.rb
Trackerapp::Application.routes.draw do

  root to: "entries#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  resources :entries do
    get :autocomplete_project_name, :on => :collection
  end

  get 'settings', to: 'users#edit'

  resource :user do
    collection do
      patch :update_settings
      post :update_settings
      get :update_settings
      patch :update_password
      get :update_password
      post :update_password
    end
  end

  namespace :admin do
    get '/' => "admin#index"
    resources :projects
    resources :users
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :entries
  has_many :project_users
  has_many :users, :through => :project_users

  validates :name, :presence => true, :allow_nil => false

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to admin_path, :notice => t('projects.project_created')
    else
      render :index
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to admin_path, :notice => t('projects.project_updated')
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to admin_path, :notice => t('projects.project_deleted')
  end

  def show
    @project = Project.find(params[:id])

    @from = if params[:from].present?
              Date.parse(params[:from])
            else
              Date.new(Date.current.year, Date.current.month, 1)
            end

    @previous_month = (@from - 1.month).at_beginning_of_month
    @next_month = (@from + 1.month).at_beginning_of_month

    @entries = Entry.for_project(@project).between(@from, @next_month).by_date
    @total = @entries.sum(:minutes)
  end

  private

  def project_params
    params.require(:project).permit!
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin

  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
    @users = User.all

    @project ||= Project.new
  end

  def show
    @project = Project.find(params[:id])

    @from = if params[:from]
      Date.strptime(params[:from], '%d/%m/%Y')
    else
      Date.new(Date.today.year, Date.today.month, 1)
    end

    @previous_month = (@from - 1.month).at_beginning_of_month
    @next_month = (@from + 1.month).at_beginning_of_month

    @entries = @project.entries.where('date >= ?', @from).where('date < ?', @next_month).order('date desc')

    @total = @entries.sum(:minutes)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path, :notice => "Project updated."
    else
      render 'edit'
    end
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, :notice => "Project created."
    else
      index
      render :index
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :user_tokens)
  end

  def require_admin
    unless current_user.admin?
      flash[:error] = "You must be admin to access this section"
      redirect_to root_url
    end
  end
end

app/views/admin/projects/_form.html.slim
= form_for [:admin, @project], html: { id: 'admin-project-form', class: 'form-horizontal' } do |f|

  = render 'layouts/errors', object: @project

  .form-group
    = f.label :name, t('projects.name'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :users, t('projects.users'), class: 'col-sm-4 control-label'
    .col-sm-4
      = f.collection_select :user_ids, User.all, :id, :username, { include_blank: true }, { multiple: true, class: 'form-control'}

  .form-group
    .col-sm-offset-4.col-sm-4
      = f.submit t('projects.save'), class: 'btn btn-default'


javascript:
  $(function() {
    new AdminProjectForm($('#admin-project-form'))
  })

app/views/admin/projects/_pagination.html.slim
div class="box-nav pagination-#{position}"

  = link_to admin_project_path(@project, from: @previous_month.to_s(:db)), class: 'btn-box' do
    = l(@previous_month, :format => "%B")

  span.btn-box = l(@from, :format => "%B")

  = link_to admin_project_path(@project, from: @next_month.to_s(:db)), class: 'btn-box' do
    = l(@next_month, :format => "%B")

app/views/admin/projects/edit.html.slim
= title "#{t('common.administration')} - #{t('projects.project')} #{@project.name}"

.box

  h1 = "#{t('projects.update')} #{@project.name}"

  = render 'form'

app/views/admin/projects/new.html.slim
.box

  h1 #{t('projects.add_new_project')}

  = render 'form'

app/views/admin/projects/show.html.slim
= title "#{t('common.administration')} - #{t('projects.project')} #{@project.name}"

.container
  .well.well-sm
    b = "#{t('projects.project_name')}: #{@project.name}"
    b = "#{t('projects.assigned_users')}: #{@project.users.map(&:username).join(", ") }"

= render "entries/entries"