config/routes.rb
Trackerapp::Application.routes.draw do

  root to: "entries#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  resources :entries do
    get :autocomplete_project_name, :on => :collection
  end

  get 'settings', to: 'users#edit'

  resource :user do
    collection do
      patch :update_settings
      post :update_settings
      get :update_settings
      patch :update_password
      get :update_password
      post :update_password
    end
  end

  namespace :admin do
    get '/' => "admin#index"
    resources :projects
    resources :users
  end

end

app/views/admin/admin/index.html.slim
= title t('common.administration')

.box

  h1 = t('admin.users')

  .box-nav
    = link_to new_admin_user_path, class: 'btn-box' do
      span.glyphicon-plus #{t('admin.add_user')}

  table.table
    thead
      tr
        th #{t('admin.name')}
        th #{t('admin.email')}
        th #{t('admin.type')}
        th
    tbody
      - @users.each do |user|
        tr
          td = user.username
          td = user.email
          td = user.type_in_words
          td
            .pull-right
              = link_to admin_user_path(user), class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-zoom-in #{t('admin.view')}
              = link_to edit_admin_user_path(user), class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-pencil #{t('admin.edit')}
              = link_to admin_user_path(user), data: { confirm: t('common.are_you_sure'), method: 'delete' }, class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-trash #{t('admin.delete')}

.box

  h1 = t('admin.projects')

  .box-nav
    = link_to new_admin_project_path, class: 'btn-box' do
      span.glyphicon-plus #{t('admin.add_project')}

  table.table

    thead
      tr
        th #{t('admin.name')}
        th #{t('admin.soldiers')}
        th

    tbody
      - @projects.each do |project|
        tr
          td = project.name
          td = project.users.map(&:username).join(",")
          td
            .pull-right
              = link_to admin_project_path(project), class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-zoom-in #{t('admin.view')}
              = link_to edit_admin_project_path(project), class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-pencil #{t('admin.edit')}
              = link_to admin_project_path(project), data: { confirm: t('common.are_you_sure'), method: 'delete' }, class: 'btn btn-default btn-sm' do
                .glyphicon.glyphicon-trash #{t('admin.delete')}