config/routes.rb
Trackerapp::Application.routes.draw do

  root to: "entries#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  resources :entries do
    get :autocomplete_project_name, :on => :collection
  end

  get 'settings', to: 'users#edit'

  resource :user do
    collection do
      patch :update_settings
      post :update_settings
      get :update_settings
      patch :update_password
      get :update_password
      post :update_password
    end
  end

  namespace :admin do
    get '/' => "admin#index"
    resources :projects
    resources :users
  end

end

app/views/layouts/_errors.html.slim
- if object.errors.any?
  .alert.alert-danger
    h2 = "#{object.errors.count} #{t('common.errors', :count => object.errors.count)}:"
    ul
      - object.errors.full_messages.each do |message|
        li = message

app/views/layouts/_flash.html.slim
- flash.each do |name, message|
  .alert.flash class="alert-#{alert_kind(name)}"
    button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
    = message

app/views/layouts/_navigation.html.slim
.topnav
  - if logged_in?
    = link_to root_path, class: "nav-item #{nav_item_class('root')}", title: t('common.track_time') do
      span.icon-user

    - if current_user.admin?
      = link_to admin_path, class: "nav-item #{nav_item_class('admin')}", title: t('common.administration') do
        span.icon-users

    = link_to settings_path, class: "nav-item #{nav_item_class('settings')}", title: t('common.settings') do
      span.icon-edit

    = link_to logout_path, class: "nav-item", title: "#{t('common.log_out')}, #{current_user.username}" do
      span.icon-turnoff

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{t('common.tracker')} - #{yield(:title)}
    meta charset="utf-8"
    meta name="author" content="eBallance Creative s.r.o."
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    link href='http://fonts.googleapis.com/css?family=Average+Sans' rel='stylesheet' type='text/css'
    link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'
    = include_jquery
    = javascript_include_tag 'application-bundle'
    = stylesheet_link_tag 'application-bundle'
    = csrf_meta_tag

  body
    .container
      = render 'layouts/navigation'
      = render 'layouts/flash'
      = yield